name: test pipeline
run-name: running
on: [push, workflow_dispatch]
jobs:
  myPipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - name: setup yarn
        run: yarn
      - name: unit tests
        run: yarn test
      - name: integration tests
        run: |
          yarn build
          yarn test:e2e
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "**/reports/**/*.xml"
        if: always()
        
        
