name: test pipeline
run-name: running
on: [push, workflow_dispatch]
jobs:
  myPipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - name: setup yarn
        run: yarn
      - name: unit tests
        run: yarn test
